# Generated by Django 4.1 on 2022-08-28 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Empresa')),
                ('detalle', models.TextField(blank=True, verbose_name='Breve Reseña')),
                ('foto', models.ImageField(blank=True, upload_to='static/image', verbose_name='Foto Lugar')),
                ('propietario', models.CharField(blank=True, max_length=60, verbose_name='Propietario')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=100, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='Telefono')),
                ('celular', models.CharField(max_length=10, verbose_name='celular')),
                ('video2', models.FileField(blank=True, upload_to='static/image', verbose_name='Video')),
                ('fecha_creacion', models.DateField(default=datetime.date.today, verbose_name='Activación')),
            ],
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Ruta')),
                ('detalle', models.CharField(max_length=200, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='static/image')),
                ('nivel', models.CharField(blank=True, max_length=30, verbose_name='Nivel Ruta')),
                ('url', models.URLField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('act', models.IntegerField(default=0, verbose_name='Actividad')),
                ('length_unit', models.CharField(default='Km', max_length=5, verbose_name='Unidad')),
                ('length', models.IntegerField(default=0, verbose_name='Distancia')),
                ('near', models.CharField(blank=True, max_length=100, verbose_name='Cerca de')),
                ('author', models.CharField(default='GAD Presidente Urbina', max_length=100, verbose_name='Autor')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/Inactivo')),
            ],
        ),
        migrations.CreateModel(
            name='Foto_ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('foto', models.ImageField(upload_to='static/image', verbose_name='Foto')),
                ('fecha_crea', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('D', 'Desactivar')], default='A', max_length=1, verbose_name='Estado')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgeo.rutas', verbose_name='Ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Foto_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='static/image', verbose_name='Fotos')),
                ('fecha_ing', models.DateField(default=datetime.date.today, verbose_name='Fecha de Ingreso')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('D', 'Desactivar')], default='A', max_length=1, verbose_name='Estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgeo.empresa', verbose_name='Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgeo.rutas', verbose_name='Ruta'),
        ),
    ]
